//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//        By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

public class Problem2 {

    public static void main(String[] args) {
        System.out.println(evenFibonacciNumbers());
    }

    private static long evenFibonacciNumbers(){
        long lastNumber = 1;
        long currentNumber = 1;
        long total = 0;
        long placeHolder = 0;
        while(currentNumber <= 4000000){
            placeHolder = currentNumber;
            currentNumber += lastNumber;
            lastNumber = placeHolder;
            if(currentNumber % 2 == 0){
                total += currentNumber;
            }
        }
        return total;
    }

}
